image: node:11.6.0

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

eslint:
  script:
    - yarn eslint .
  only:
    - merge_requests

flow:
  script:
    - yarn flow
  only:
    - merge_requests
