image: node:11.6.0

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

stages:
  - code_style

eslint:
  stage: code_style
  script:
    - yarn eslint .
  only:
    - merge_requests

flow:
  stage: code_style
  script:
    - yarn flow
  only:
    - merge_requests
