image: node:11.6.0

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

job:
  except:
    - merge_requests

stages:
  - lint

eslint:
  stage: lint
  script:
    - yarn eslint .
